baseURL = 'https://lhy099.github.io/boba-github.io/'
languageCode = 'zh-cn'
title = 'Lhy099 博客'

[params]
  author = 'Lhy099'
  description = '每日精选新闻与技术分享'

[menu]
  [[menu.main]]
    identifier = 'home'
    name = '首页'
    url = '/'
    weight = 10
  [[menu.main]]
    identifier = 'posts'
    name = '文章'
    url = '/posts/'
    weight = 20
